version: '3.8'

services:
  iframe-seo-dev:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - /app/__pycache__
      - /app/.git
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_RUN_ON_SAVE=true
      - STREAMLIT_SERVER_FILE_WATCHER_TYPE=poll
    command: ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0", "--server.runOnSave=true"]
    restart: unless-stopped